app:
  datasource:
    main:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=azeniadb
      password: BadassPassword##@
      pool-size: 30
      username: azenia_user

server:
  error:
    include-binding-errors: always
    include-message: always


# curl -XGET http://localhost:8080/fetch-top-15 | json_pp
# curl -XGET http://localhost:8080/fetch-route-count/15.5 | json_pp
# curl -XGET http://localhost:8080/fetch-routes/web/mo | json_pp


