app:
  datasource:
    main:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=somedb
      password: some_password
      pool-size: 30
      username: some_user

server:
  error:
    include-binding-errors: always
    include-message: always


